# filename: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.3

# TODO: remove
AbcSize:
  Enabled: false

# TODO: remove
ClassLength:
  Enabled: false

Documentation:
  Enabled: true

LineLength:
  Exclude:
    - '**/*.rake'
    - '**/experiments/*.rb'

# TODO: lower to 15
MethodLength:
  Max: 25

StringLiterals:
  EnforcedStyle: single_quotes

WordArray:
  Enabled: true
