# filename: .rubocop.yml

AbcSize:
  Enabled: false

ClassLength:
  Enabled: false

Documentation:
  Enabled: true

DotPosition:
  Enabled: false

HandleExceptions:
  Enabled: false

IfUnlessModifier:
  Enabled: false

LineLength:
  Exclude:
    - '**/*.rake'

MethodLength:
  Max: 25

PredicateName:
  Enabled: false

RegexpLiteral:
  Enabled: false

StringLiterals:
  EnforcedStyle: single_quotes

Style/GuardClause:
  Enabled: false

WordArray:
  Enabled: true